### ISSUE TITLE
Modifying janus to work on cloud run

### ISSUE THREAD

**Issue by MattHardner** [doitintl/janus#3]
I'd like to submit a modification for janus to be able to run on serverless (cloud run), as currently, janus requires a compute engine instance for metadata.

**Comment by Burekasim** [comment]
Hi @MattHardner 

What's the error you receive? 
The first issue would be with the instance_id (line 33). Can you try to set a string instead?

**Comment by MattHardner** [comment]
I just get an invalid access key when accessing AWS which I assumed was because serverless doesn't have access to the underlying node. It seems to be failing silently.

**Comment by Burekasim** [comment]
Can you share with me the exact error? 
I replaced line 33 with "instance_name = unknown" and I received temporary credentials from AWS.

**Comment by MattHardner** [comment]
Here is the error:
`InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
    at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)`
    
    Could you please provide the dockerfile and script you are using for cloud run that is giving valid credentials? I might be doing something silly on my side.

**Comment by MattHardner** [comment]
Disregard the above. The error I'm getting after commenting out line 33 is `Error when retrieving credentials from custom-process: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/project/project-id (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f008dedae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

I can get the project_id in another way, issue will be how to get the token without the metadata server.
